<?php
/**
 * Stripe card testing alert email footer template.
 *
 * This template can be overridden by copying it to yourtheme/wpforms/emails/stripe-card-testing-alert-footer.php.
 *
 * @since 2.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

?>

									</td>
								</tr>
								<tr>
									<td align="<?php echo is_rtl() ? 'right' : 'left'; ?>" valign="top" class="footer">
										<?php
										printf(
											/* translators: %s - site name. */
											esc_html__( 'This email was auto-generated by WPForms and sent from %s.', 'wpforms-lite' ),
											'<a href="' . esc_url( home_url() ) . '">' . esc_html( wp_specialchars_decode( get_bloginfo( 'name' ) ) ) . '</a>' // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
										);
										?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
		</td>
		<td><!-- Deliberately empty to support consistent sizing and layout across multiple email clients. --></td>
	</tr>
</table>
</body>
</html>
