<?php
/**
 * Stripe card testing alert email footer template (plain text).
 *
 * This template can be overridden by copying it to yourtheme/wpforms/emails/stripe-card-testing-alert-footer-plain.php.
 *
 * @since 2.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

echo "\n---\n\n";
printf(
	/* translators: %s - site name. */
	esc_html__( 'This email was auto-generated by WPForms and sent from %s.', 'wpforms-lite' ),
	esc_html( wp_specialchars_decode( get_bloginfo( 'name' ) ) )
);
echo "\n";
