<?php
/**
 *  Define the main autoloader
 *
 * @link       https://searchandfilter.com
 * @since      3.0.0
 *
 * @package    Search_Filter_Pro
 */

spl_autoload_register( 'search_filter_pro_autoloader' );

// Load scoped vendor dependencies (Porter Stemmer, etc.).
// Note: Generated by generate-vendor-classmap.php after php-scoper runs.
$vendor_autoload = plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';
if ( file_exists( $vendor_autoload ) ) {
	require_once $vendor_autoload;
}

/**
 * PHP auto loader function
 *
 * Supports classes, interfaces, and traits with naming conventions:
 * - class-{name}.php for classes
 * - interface-{name}.php for interfaces
 * - trait-{name}.php for traits
 *
 * @param string $class_name  PHP Class name with namespace.
 * @return void
 */
function search_filter_pro_autoloader( $class_name ) {
	$parent_namespace = 'Search_Filter_Pro';
	if ( false !== strpos( $class_name, $parent_namespace ) ) {
		$classes_dir = realpath( plugin_dir_path( __FILE__ ) ) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR;

		// Project namespace & length.
		$project_namespace = $parent_namespace . '\\';
		$length            = strlen( $project_namespace );

		// Remove top level namespace (that is the current dir).
		$class_file = substr( $class_name, $length );
		// Swap underscores for dashes and lowercase.
		$class_file = str_replace( '_', '-', strtolower( $class_file ) );

		// Build path parts.
		$class_parts = explode( '\\', $class_file );
		$last_index  = count( $class_parts ) - 1;
		$base_name   = $class_parts[ $last_index ];

		// Try different prefixes: class-, interface-, trait-.
		$prefixes = array( 'class-', 'interface-', 'trait-' );

		foreach ( $prefixes as $prefix ) {
			$class_parts[ $last_index ] = $prefix . $base_name;
			$class_file                 = implode( DIRECTORY_SEPARATOR, $class_parts ) . '.php';
			$location                   = $classes_dir . $class_file;

			if ( is_file( $location ) ) {
				require_once $location;
				return;
			}
		}
	}
}
